// frontend-vue/src/views/Questioning.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import {
  Plus,
  Edit,
  Delete,
  Search,
  Connection,
  ChatLineRound,
  Document
} from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'
import type { DatabaseSource, GlossaryTerm, QuestionHistory } from '../types'
import type { DatabaseSourceCreate, GlossaryTermCreate } from '../types'
import { questioningApi } from '../services/api'

const { t } = useI18n()

const activeTab = ref('databases')

// Databases State
const dbLoading = ref(false)
const databases = ref<DatabaseSource[]>([])
const dbModalVisible = ref(false)
const editingDb = ref<DatabaseSource | null>(null)
const dbFormData = ref<DatabaseSourceCreate>({
  name: '',
  type: 'MySQL',
  host: '',
  port: 3306,
  database: '',
  username: '',
  password: ''
})

// Glossaries State
const glossaryLoading = ref(false)
const glossaries = ref<GlossaryTerm[]>([])
const glossaryModalVisible = ref(false)
const editingGlossary = ref<GlossaryTerm | null>(null)
const glossaryFormData = ref<GlossaryTermCreate>({
  term: '',
  definition: '',
  mapping: '',
  category: '销售指标',
  example: ''
})
const searchKeyword = ref('')

// History State
const historyLoading = ref(false)
const questionHistory = ref<QuestionHistory[]>([])

// Natural Language Ask State
const selectedDatabase = ref<string>()
const questionText = ref('')
const askLoading = ref(false)
const generatedSQL = ref('')
const questionExplanation = ref('')
const questionConfidence = ref(0)
const recognizedTerms = ref<string[]>([])

// Fetch databases
const fetchDatabases = async () => {
  try {
    dbLoading.value = true
    const response = await questioningApi.getDatabases()
    // Transform snake_case to camelCase if needed
    databases.value = (response.databases || []).map((db: any) => ({
      ...db,
      tableCount: db.tableCount || db.table_count || 0,
      lastSync: db.lastSync || db.last_sync || '',
      status: db.status || 'unknown'
    }))
  } catch (error) {
    console.error('Failed to fetch databases:', error)
    ElMessage.error(t('questioning.databases.fetchFailed'))
  } finally {
    dbLoading.value = false
  }
}

// Handle database add/edit
const handleDbAdd = () => {
  editingDb.value = null
  dbFormData.value = {
    name: '',
    type: 'MySQL',
    host: '',
    port: 3306,
    database: '',
    username: '',
    password: ''
  }
  dbModalVisible.value = true
}

const handleDbEdit = (record: DatabaseSource) => {
  editingDb.value = record
  dbFormData.value = {
    name: record.name,
    type: record.type,
    host: record.host,
    port: record.port,
    database: record.database,
    username: record.username,
    password: ''
  }
  dbModalVisible.value = true
}

const handleDbDelete = async (id: string) => {
  try {
    await questioningApi.deleteDatabase(id)
    ElMessage.success(t('questioning.databases.deleteSuccess'))
    fetchDatabases()
  } catch (error) {
    ElMessage.error(t('questioning.databases.deleteFailed'))
  }
}

const handleDbSubmit = async () => {
  try {
    if (editingDb.value) {
      await questioningApi.updateDatabase(editingDb.value.id, dbFormData.value)
      ElMessage.success(t('questioning.databases.updateSuccess'))
    } else {
      await questioningApi.createDatabase(dbFormData.value)
      ElMessage.success(t('questioning.databases.createSuccess'))
    }
    dbModalVisible.value = false
    fetchDatabases()
  } catch (error) {
    ElMessage.error(editingDb.value ? t('questioning.databases.updateFailed') : t('questioning.databases.createFailed'))
  }
}

// Fetch glossaries
const fetchGlossaries = async () => {
  try {
    glossaryLoading.value = true
    const response = await questioningApi.getGlossaries()
    // Ensure all fields have default values
    glossaries.value = (response.glossaries || []).map((item: any) => ({
      ...item,
      term: item.term || '',
      definition: item.definition || '',
      mapping: item.mapping || '',
      category: item.category || '',
      example: item.example || '',
      created_at: item.created_at || new Date().toISOString(),
      updated_at: item.updated_at
    }))
  } catch (error) {
    console.error('Failed to fetch glossaries:', error)
    ElMessage.error(t('questioning.glossaries.fetchFailed'))
  } finally {
    glossaryLoading.value = false
  }
}

// Handle glossary add/edit
const handleGlossaryAdd = () => {
  editingGlossary.value = null
  glossaryFormData.value = {
    term: '',
    definition: '',
    mapping: '',
    category: '销售指标',
    example: ''
  }
  glossaryModalVisible.value = true
}

const handleGlossaryEdit = (record: GlossaryTerm) => {
  editingGlossary.value = record
  glossaryFormData.value = {
    term: record.term,
    definition: record.definition,
    mapping: record.mapping,
    category: record.category,
    example: record.example
  }
  glossaryModalVisible.value = true
}

const handleGlossaryDelete = async (id: string) => {
  try {
    await questioningApi.deleteGlossary(id)
    ElMessage.success(t('questioning.glossaries.deleteSuccess'))
    fetchGlossaries()
  } catch (error) {
    ElMessage.error(t('questioning.glossaries.deleteFailed'))
  }
}

const handleGlossarySubmit = async () => {
  try {
    if (editingGlossary.value) {
      await questioningApi.updateGlossary(editingGlossary.value.id, glossaryFormData.value)
      ElMessage.success(t('questioning.glossaries.updateSuccess'))
    } else {
      await questioningApi.createGlossary(glossaryFormData.value)
      ElMessage.success(t('questioning.glossaries.createSuccess'))
    }
    glossaryModalVisible.value = false
    fetchGlossaries()
  } catch (error) {
    ElMessage.error(editingGlossary.value ? t('questioning.glossaries.updateFailed') : t('questioning.glossaries.createFailed'))
  }
}

// Fetch history
const fetchHistory = async () => {
  try {
    historyLoading.value = true
    const response = await questioningApi.getHistories(0, 50)
    // Transform data and handle potential missing fields
    questionHistory.value = (response.histories || []).map((item: any) => ({
      ...item,
      duration: item.duration || 0,
      status: item.status || 'unknown',
      database_name: item.database_name || item.databaseName || '',
      created_at: item.created_at || new Date().toISOString()
    }))
  } catch (error) {
    console.error('Failed to fetch history:', error)
    ElMessage.error(t('questioning.history.fetchFailed'))
  } finally {
    historyLoading.value = false
  }
}

// Handle ask question
const handleAskQuestion = async () => {
  if (!selectedDatabase.value) {
    ElMessage.warning(t('questioning.ask.noDatabase'))
    return
  }
  if (!questionText.value.trim()) {
    ElMessage.warning(t('questioning.ask.questionRequired'))
    return
  }

  try {
    askLoading.value = true
    const response = await questioningApi.askQuestion({
      question: questionText.value,
      database_id: selectedDatabase.value
    })
    generatedSQL.value = response.sql
    questionExplanation.value = response.explanation
    questionConfidence.value = response.confidence
    recognizedTerms.value = response.glossaries || []
    ElMessage.success(t('questioning.ask.askSuccess'))
  } catch (error) {
    ElMessage.error(t('questioning.ask.askFailed'))
  } finally {
    askLoading.value = false
  }
}

// Helper functions
const getStatusType = (status?: string) => {
  if (!status) return 'info'
  return status === 'connected' ? 'success' : 'danger'
}

const getStatusText = (status?: string) => {
  if (!status) return t('questioning.databases.statusUnknown')
  return status === 'connected' ? t('questioning.databases.statusConnected') : t('questioning.databases.statusDisconnected')
}

// Watch tab changes
const handleTabChange = (tabName: string) => {
  if (tabName === 'databases') {
    fetchDatabases()
  } else if (tabName === 'glossaries') {
    fetchGlossaries()
  } else if (tabName === 'history') {
    fetchHistory()
  }
}

onMounted(() => {
  fetchDatabases()
})
</script>

<template>
  <div class="page-container">
    <div class="page-header">
      <h1 class="page-title">{{ t('questioning.title') }}</h1>
    </div>

    <el-tabs v-model="activeTab" type="border-card" @tab-change="handleTabChange">
      <!-- Databases Tab -->
      <el-tab-pane :label="t('questioning.tabs.databases')" name="databases">
        <div class="table-header">
          <el-alert
            :title="t('questioning.databases.alertMessage')"
            :description="t('questioning.databases.alertDescription')"
            type="info"
            show-icon
            :closable="false"
          />
          <el-button type="primary" :icon="Plus" @click="handleDbAdd">
            {{ t('questioning.databases.addButton') }}
          </el-button>
        </div>

        <el-table
          v-loading="dbLoading"
          :data="databases"
          stripe
          style="width: 100%"
        >
          <el-table-column prop="name" :label="t('questioning.databases.name')" min-width="130" header-align="center" />
          <el-table-column prop="type" :label="t('questioning.databases.type')" width="100" header-align="center" />
          <el-table-column prop="host" :label="t('questioning.databases.host')" min-width="140" header-align="center" />
          <el-table-column prop="port" :label="t('questioning.databases.port')" width="70" header-align="center" />
          <el-table-column prop="database" :label="t('questioning.databases.database')" min-width="110" header-align="center" />
          <el-table-column :label="t('questioning.databases.status')" width="90" header-align="center">
            <template #default="{ row }">
              <el-tag :type="getStatusType(row.status)" size="small">
                {{ getStatusText(row.status) }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('questioning.databases.tableCount')" width="80" header-align="center">
            <template #default="{ row }">
              {{ row.tableCount || 0 }}
            </template>
          </el-table-column>
          <el-table-column :label="t('common.actions')" width="150" fixed="right" header-align="center">
            <template #default="{ row }">
              <el-button
                type="primary"
                size="small"
                :icon="Edit"
                link
                @click="handleDbEdit(row)"
              >
                {{ t('common.edit') }}
              </el-button>
              <el-button
                type="danger"
                size="small"
                :icon="Delete"
                link
                @click="handleDbDelete(row.id)"
              >
                {{ t('common.delete') }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <!-- Glossaries Tab -->
      <el-tab-pane :label="t('questioning.tabs.glossaries')" name="glossaries">
        <div class="table-header">
          <el-input
            v-model="searchKeyword"
            :placeholder="t('questioning.glossaries.searchPlaceholder')"
            clearable
            style="width: 300px"
          >
            <template #append>
              <el-button :icon="Search" />
            </template>
          </el-input>
          <el-button type="primary" :icon="Plus" @click="handleGlossaryAdd">
            {{ t('questioning.glossaries.addButton') }}
          </el-button>
        </div>

        <el-table
          v-loading="glossaryLoading"
          :data="glossaries.filter(g => !searchKeyword || g.term.includes(searchKeyword))"
          stripe
          style="width: 100%"
        >
          <el-table-column prop="term" :label="t('questioning.glossaries.term')" min-width="130" header-align="center" />
          <el-table-column prop="definition" :label="t('questioning.glossaries.definition')" min-width="180" show-overflow-tooltip header-align="center" />
          <el-table-column prop="mapping" :label="t('questioning.glossaries.mapping')" min-width="140" show-overflow-tooltip header-align="center" />
          <el-table-column prop="category" :label="t('questioning.glossaries.category')" min-width="100" header-align="center" />
          <el-table-column :label="t('common.actions')" width="150" fixed="right" header-align="center">
            <template #default="{ row }">
              <el-button
                type="primary"
                size="small"
                :icon="Edit"
                link
                @click="handleGlossaryEdit(row)"
              >
                {{ t('common.edit') }}
              </el-button>
              <el-button
                type="danger"
                size="small"
                :icon="Delete"
                link
                @click="handleGlossaryDelete(row.id)"
              >
                {{ t('common.delete') }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <!-- History Tab -->
      <el-tab-pane :label="t('questioning.tabs.history')" name="history">
        <el-alert
          :title="t('questioning.history.alertMessage')"
          :description="t('questioning.history.alertDescription')"
          type="info"
          show-icon
          :closable="false"
          class="mb-16"
        />

        <el-table
          v-loading="historyLoading"
          :data="questionHistory"
          stripe
          style="width: 100%"
        >
          <el-table-column prop="question" :label="t('questioning.history.question')" min-width="220" show-overflow-tooltip header-align="center" />
          <el-table-column prop="sql" :label="t('questioning.history.sql')" min-width="260" show-overflow-tooltip header-align="center" />
          <el-table-column :label="t('questioning.history.duration')" width="90" header-align="center">
            <template #default="{ row }">
              {{ row.duration ? `${row.duration}ms` : '-' }}
            </template>
          </el-table-column>
          <el-table-column :label="t('questioning.history.status')" width="90" header-align="center">
            <template #default="{ row }">
              <el-tag
                :type="row.status === 'success' ? 'success' : row.status === 'failed' ? 'danger' : 'info'"
                size="small"
              >
                {{ row.status === 'success' ? t('questioning.history.statusSuccess') : row.status === 'failed' ? t('questioning.history.statusFailed') : t('questioning.history.statusUnknown') }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="database_name" :label="t('questioning.history.database')" min-width="110" header-align="center" />
          <el-table-column prop="created_at" :label="t('questioning.history.askTime')" width="170" header-align="center">
            <template #default="{ row }">
              {{ new Date(row.created_at).toLocaleString('zh-CN') }}
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <!-- Natural Language Ask Tab -->
      <el-tab-pane :label="t('questioning.tabs.ask')" name="ask">
        <el-row :gutter="24">
          <el-col :span="12">
            <el-card>
              <template #header>
                <div class="card-header">
                  <el-icon><ChatLineRound /></el-icon>
                  <span>{{ t('questioning.ask.title') }}</span>
                </div>
              </template>

              <el-form label-width="120px">
                <el-form-item :label="t('questioning.ask.selectDatabase')" required>
                  <el-select
                    v-model="selectedDatabase"
                    :placeholder="t('questioning.ask.selectDatabase')"
                    style="width: 100%"
                  >
                    <el-option
                      v-for="db in databases.filter(d => d.status === 'connected')"
                      :key="db.id"
                      :label="db.name"
                      :value="db.id"
                    />
                  </el-select>
                </el-form-item>

                <el-form-item :label="t('questioning.ask.questionLabel')" required>
                  <el-input
                    v-model="questionText"
                    type="textarea"
                    :rows="4"
                    :placeholder="t('questioning.ask.questionPlaceholder')"
                  />
                </el-form-item>

                <el-form-item>
                  <el-button
                    type="primary"
                    :loading="askLoading"
                    @click="handleAskQuestion"
                  >
                    {{ t('questioning.ask.askButton') }}
                  </el-button>
                  <el-button @click="generatedSQL = ''; questionText = ''">
                    {{ t('questioning.ask.clearButton') }}
                  </el-button>
                </el-form-item>
              </el-form>

              <el-divider />

              <div>
                <h4>{{ t('questioning.ask.exampleLabel') }}</h4>
                <p>{{ t('questioning.ask.example1') }}</p>
                <p>{{ t('questioning.ask.example2') }}</p>
                <p>{{ t('questioning.ask.example3') }}</p>
              </div>
            </el-card>
          </el-col>

          <el-col :span="12">
            <el-card v-if="generatedSQL">
              <template #header>
                <div class="card-header">
                  <el-icon><Document /></el-icon>
                  <span>{{ t('questioning.ask.resultTitle') }}</span>
                </div>
              </template>

              <div class="result-section">
                <h4>{{ t('questioning.ask.generatedSQL') }}</h4>
                <el-input
                  v-model="generatedSQL"
                  type="textarea"
                  :rows="6"
                  readonly
                />

                <h4 class="mt-16">{{ t('questioning.ask.explanation') }}</h4>
                <p>{{ questionExplanation }}</p>

                <el-row :gutter="16" class="mt-16">
                  <el-col :span="12">
                    <el-statistic :title="t('questioning.ask.confidence')" :value="(questionConfidence * 100).toFixed(1)" suffix="%" />
                  </el-col>
                  <el-col :span="12">
                    <div>{{ t('questioning.ask.recognizedTerms') }}:</div>
                    <el-tag
                      v-for="term in recognizedTerms"
                      :key="term"
                      size="small"
                      style="margin-right: 4px; margin-top: 8px"
                    >
                      {{ term }}
                    </el-tag>
                  </el-col>
                </el-row>
              </div>
            </el-card>
          </el-col>
        </el-row>
      </el-tab-pane>
    </el-tabs>

    <!-- Database Modal -->
    <el-dialog
      v-model="dbModalVisible"
      :title="editingDb ? t('questioning.databases.editModalTitle') : t('questioning.databases.addModalTitle')"
      width="600px"
    >
      <el-form :model="dbFormData" label-width="120px">
        <el-form-item :label="t('questioning.databases.nameLabel')" required>
          <el-input v-model="dbFormData.name" :placeholder="t('questioning.databases nameLabel')" />
        </el-form-item>

        <el-form-item :label="t('questioning.databases.typeLabel')" required>
          <el-select v-model="dbFormData.type" style="width: 100%">
            <el-option value="MySQL" />
            <el-option value="PostgreSQL" />
            <el-option value="Oracle" />
            <el-option value="SQLServer" />
          </el-select>
        </el-form-item>

        <el-form-item :label="t('questioning.databases.hostLabel')" required>
          <el-input v-model="dbFormData.host" :placeholder="t('questioning.databases.hostPlaceholder')" />
        </el-form-item>

        <el-form-item :label="t('questioning.databases.portLabel')" required>
          <el-input-number v-model="dbFormData.port" :min="1" :max="65535" style="width: 100%" />
        </el-form-item>

        <el-form-item :label="t('questioning.databases.databaseLabel')" required>
          <el-input v-model="dbFormData.database" />
        </el-form-item>

        <el-form-item :label="t('questioning.databases.usernameLabel')" required>
          <el-input v-model="dbFormData.username" />
        </el-form-item>

        <el-form-item :label="t('questioning.databases.passwordLabel')">
          <el-input v-model="dbFormData.password" type="password" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="dbModalVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" @click="handleDbSubmit">{{ t('common.confirm') }}</el-button>
      </template>
    </el-dialog>

    <!-- Glossary Modal -->
    <el-dialog
      v-model="glossaryModalVisible"
      :title="editingGlossary ? t('questioning.glossaries.editModalTitle') : t('questioning.glossaries.addModalTitle')"
      width="600px"
    >
      <el-form :model="glossaryFormData" label-width="120px">
        <el-form-item :label="t('questioning.glossaries.termLabel')" required>
          <el-input v-model="glossaryFormData.term" :placeholder="t('questioning.glossaries.termPlaceholder')" />
        </el-form-item>

        <el-form-item :label="t('questioning.glossaries.definitionLabel')" required>
          <el-input v-model="glossaryFormData.definition" type="textarea" :rows="2" />
        </el-form-item>

        <el-form-item :label="t('questioning.glossaries.mappingLabel')" required>
          <el-input v-model="glossaryFormData.mapping" :placeholder="t('questioning.glossaries.mappingPlaceholder')" />
        </el-form-item>

        <el-form-item :label="t('questioning.glossaries.categoryLabel')" required>
          <el-select v-model="glossaryFormData.category" style="width: 100%">
            <el-option :label="t('questioning.glossaries.categorySales')" value="销售指标" />
            <el-option :label="t('questioning.glossaries.categoryUser')" value="用户指标" />
            <el-option :label="t('questioning.glossaries.categoryProduct')" value="产品指标" />
            <el-option :label="t('questioning.glossaries.categoryFinance')" value="财务指标" />
          </el-select>
        </el-form-item>

        <el-form-item :label="t('questioning.glossaries.exampleLabel')" required>
          <el-input v-model="glossaryFormData.example" :placeholder="t('questioning.glossaries.examplePlaceholder')" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="glossaryModalVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" @click="handleGlossarySubmit">{{ t('common.confirm') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
}

.result-section h4 {
  margin-bottom: 8px;
  font-weight: 600;
  color: #111827;
}
</style>

// frontend/src/pages/Questioning.tsx
import React, { useEffect, useState, useMemo } from 'react';
import {
  Table,
  Button,
  Space,
  Modal,
  Form,
  Input,
  Select,
  Tag,
  message,
  Popconfirm,
  Card,
  Row,
  Col,
  Statistic,
  Tabs,
  Alert,
  Descriptions,
  Progress,
} from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  DatabaseOutlined,
  BookOutlined,
  HistoryOutlined,
  PlayCircleOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
} from '@ant-design/icons';
// @ts-expect-error - Types are used for type checking
import type { DatabaseSource, GlossaryTerm, QuestionHistory } from '../types';
import { questioningApi } from '../services/api';
import { useTranslation } from '../contexts/LanguageContext';
import { createTranslateProxy } from '../utils/i18n';

const { TextArea } = Input;
const { Search } = Input;

const QuestioningPage: React.FC = () => {
  const { t } = useTranslation();
  const tp = useMemo(() => createTranslateProxy(t), [t]);
  const [activeTab, setActiveTab] = useState('databases');

  // 数据库管理状态
  const [databases, setDatabases] = useState<any[]>([]);
  const [dbModalVisible, setDbModalVisible] = useState(false);
  const [editingDb, setEditingDb] = useState<any>(null);
  const [dbForm] = Form.useForm();

  // 行业黑话状态
  const [glossaries, setGlossaries] = useState<any[]>([]);
  const [glossaryModalVisible, setGlossaryModalVisible] = useState(false);
  const [glossaryForm] = Form.useForm();

  // 问数历史状态
  const [histories, setHistories] = useState<any[]>([]);

  // 问答测试状态
  const [question, setQuestion] = useState('');
  const [testResult, setTestResult] = useState<any>(null);
  const [testing, setTesting] = useState(false);

  useEffect(() => {
    if (activeTab === 'databases') {
      fetchDatabases();
    } else if (activeTab === 'glossaries') {
      fetchGlossaries();
    } else if (activeTab === 'history') {
      fetchHistories();
    }
  }, [activeTab]);

  // ==================== 数据库管理 ====================
  const fetchDatabases = async () => {
    try {
      const response = await questioningApi.getDatabases();
      setDatabases(response.databases || []);
    } catch (error) {
      message.error(tp('questioning.databases.fetchFailed'));
    }
  };

  const handleAddDb = () => {
    setEditingDb(null);
    dbForm.resetFields();
    setDbModalVisible(true);
  };

  const handleEditDb = (record: any) => {
    setEditingDb(record);
    dbForm.setFieldsValue(record);
    setDbModalVisible(true);
  };

  const handleDeleteDb = async (id: string) => {
    try {
      await questioningApi.deleteDatabase(id);
      message.success(tp('questioning.databases.deleteSuccess'));
      fetchDatabases();
    } catch (error) {
      message.error(tp('questioning.databases.deleteFailed'));
    }
  };

  const handleSubmitDb = async () => {
    try {
      const values = await dbForm.validateFields();

      if (editingDb) {
        await questioningApi.updateDatabase(editingDb.id, values);
        message.success(tp('questioning.databases.updateSuccess'));
      } else {
        await questioningApi.createDatabase(values);
        message.success(tp('questioning.databases.createSuccess'));
      }

      setDbModalVisible(false);
      dbForm.resetFields();
      fetchDatabases();
    } catch (error) {
      message.error(editingDb ? tp('questioning.databases.updateFailed') : tp('questioning.databases.createFailed'));
    }
  };

  const handleTestConnection = async (db_id: string) => {
    try {
      message.loading(tp('questioning.databases.testConnecting'), 0);
      await questioningApi.testConnection(db_id);
      message.destroy();
      message.success(tp('questioning.databases.testSuccess'));
      fetchDatabases();
    } catch (error) {
      message.destroy();
      message.error(tp('questioning.databases.testFailed'));
    }
  };

  const databaseColumns = [
    {
      title: tp('questioning.databases.name'),
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: tp('questioning.databases.type'),
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => <Tag color="blue">{type}</Tag>,
    },
    {
      title: tp('questioning.databases.host'),
      dataIndex: 'host',
      key: 'host',
    },
    {
      title: tp('questioning.databases.port'),
      dataIndex: 'port',
      key: 'port',
    },
    {
      title: tp('questioning.databases.database'),
      dataIndex: 'database',
      key: 'database',
    },
    {
      title: tp('questioning.databases.status'),
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => (
        <Tag color={status === 'connected' ? 'success' : 'error'} icon={status === 'connected' ? <CheckCircleOutlined /> : <CloseCircleOutlined />}>
          {status === 'connected' ? tp('questioning.databases.statusConnected') : tp('questioning.databases.statusDisconnected')}
        </Tag>
      ),
    },
    {
      title: tp('questioning.databases.tableCount'),
      dataIndex: 'tableCount',
      key: 'tableCount',
    },
    {
      title: tp('questioning.databases.lastSync'),
      dataIndex: 'lastSync',
      key: 'lastSync',
    },
    {
      title: tp('common.actions'),
      key: 'action',
      render: (_: any, record: any) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<PlayCircleOutlined />}
            onClick={() => handleTestConnection(record.id)}
          >
            {tp('questioning.databases.testConnection')}
          </Button>
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEditDb(record)}
          >
            {tp('common.edit')}
          </Button>
          <Popconfirm
            title={tp('questioning.databases.deleteConfirm')}
            onConfirm={() => handleDeleteDb(record.id)}
            okText={tp('common.confirm')}
            cancelText={tp('common.cancel')}
          >
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>
              {tp('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ==================== 行业黑话管理 ====================
  const fetchGlossaries = async () => {
    try {
      const response = await questioningApi.getGlossaries();
      setGlossaries(response.glossaries || []);
    } catch (error) {
      message.error(tp('questioning.glossaries.fetchFailed'));
    }
  };

  const handleAddGlossary = () => {
    glossaryForm.resetFields();
    setGlossaryModalVisible(true);
  };

  const handleEditGlossary = (record: any) => {
    glossaryForm.setFieldsValue(record);
    setGlossaryModalVisible(true);
  };

  const handleDeleteGlossary = async (id: string) => {
    try {
      await questioningApi.deleteGlossary(id);
      message.success(tp('questioning.glossaries.deleteSuccess'));
      fetchGlossaries();
    } catch (error) {
      message.error(tp('questioning.glossaries.deleteFailed'));
    }
  };

  const handleSubmitGlossary = async () => {
    try {
      const values = await glossaryForm.validateFields();
      await questioningApi.createGlossary(values);
      setGlossaryModalVisible(false);
      glossaryForm.resetFields();
      fetchGlossaries();
      message.success(tp('questioning.glossaries.createSuccess'));
    } catch (error) {
      message.error(tp('questioning.glossaries.createFailed'));
    }
  };

  const glossaryColumns = [
    {
      title: tp('questioning.glossaries.term'),
      dataIndex: 'term',
      key: 'term',
      render: (term: string) => <Tag color="purple" style={{ fontSize: 14 }}>{term}</Tag>,
    },
    {
      title: tp('questioning.glossaries.definition'),
      dataIndex: 'definition',
      key: 'definition',
    },
    {
      title: tp('questioning.glossaries.mapping'),
      dataIndex: 'mapping',
      key: 'mapping',
      render: (mapping: string) => <Tag color="geekblue">{mapping}</Tag>,
    },
    {
      title: tp('questioning.glossaries.category'),
      dataIndex: 'category',
      key: 'category',
      render: (category: string) => <Tag color="blue">{category}</Tag>,
    },
    {
      title: tp('questioning.glossaries.example'),
      dataIndex: 'example',
      key: 'example',
      ellipsis: true,
    },
    {
      title: tp('common.actions'),
      key: 'action',
      render: (_: any, record: any) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEditGlossary(record)}
          >
            {tp('common.edit')}
          </Button>
          <Popconfirm
            title={tp('questioning.glossaries.deleteConfirm')}
            onConfirm={() => handleDeleteGlossary(record.id)}
            okText={tp('common.confirm')}
            cancelText={tp('common.cancel')}
          >
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>
              {tp('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ==================== 问数历史 ====================
  const fetchHistories = async () => {
    try {
      const response = await questioningApi.getHistories(0, 10);
      setHistories(response.histories || []);
    } catch (error) {
      message.error(tp('questioning.history.fetchFailed'));
    }
  };

  const historyColumns = [
    {
      title: tp('questioning.history.question'),
      dataIndex: 'question',
      key: 'question',
      width: 250,
    },
    {
      title: tp('questioning.history.sql'),
      dataIndex: 'sql',
      key: 'sql',
      width: 300,
      ellipsis: true,
    },
    {
      title: tp('questioning.history.resultCount'),
      dataIndex: 'result',
      key: 'result',
      width: 150,
      ellipsis: true,
    },
    {
      title: tp('questioning.history.duration'),
      dataIndex: 'duration',
      key: 'duration',
      width: 100,
    },
    {
      title: tp('questioning.history.status'),
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => (
        <Tag color={status === 'success' ? 'success' : 'error'} icon={status === 'success' ? <CheckCircleOutlined /> : <CloseCircleOutlined />}>
          {status === 'success' ? tp('questioning.history.statusSuccess') : tp('questioning.history.statusFailed')}
        </Tag>
      ),
    },
    {
      title: tp('questioning.history.database'),
      dataIndex: 'database',
      key: 'database',
      width: 120,
    },
    {
      title: tp('questioning.history.askTime'),
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 180,
    },
  ];

  // ==================== 问答测试 ====================
  const handleTestQuestion = async () => {
    if (!question.trim()) {
      message.warning(tp('questioning.ask.questionRequired'));
      return;
    }

    try {
      setTesting(true);
      const response = await questioningApi.askQuestion({
        question: question,
        database_id: '1' // 默认使用第一个数据库
      });
      setTestResult(response);
    } catch (error) {
      message.error(tp('questioning.ask.askFailed'));
    } finally {
      setTesting(false);
    }
  };

  // ==================== 渲染 ====================
  const tabItems = [
    {
      key: 'databases',
      label: (
        <span>
          <DatabaseOutlined />
          {tp('questioning.tabs.databases')}
        </span>
      ),
      children: (
        <Card
          title={tp('questioning.databases.title')}
          extra={
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAddDb}>
              {tp('questioning.databases.addButton')}
            </Button>
          }
        >
          <Alert
            message={tp('questioning.databases.alertMessage')}
            description={tp('questioning.databases.alertDescription')}
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <Table
            columns={databaseColumns}
            dataSource={databases}
            rowKey="id"
            pagination={false}
          />
        </Card>
      ),
    },
    {
      key: 'glossaries',
      label: (
        <span>
          <BookOutlined />
          {tp('questioning.tabs.glossaries')}
        </span>
      ),
      children: (
        <Card
          title={tp('questioning.glossaries.title')}
          extra={
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAddGlossary}>
              {tp('questioning.glossaries.addButton')}
            </Button>
          }
        >
          <Row gutter={16} style={{ marginBottom: 16 }}>
            <Col span={6}>
              <Statistic title={tp('questioning.glossaries.statsTotal')} value={glossaries.length} prefix={<BookOutlined />} />
            </Col>
            <Col span={6}>
              <Statistic title={tp('questioning.glossaries.statsSales')} value={glossaries.filter(g => g.category === tp('questioning.glossaries.categorySales')).length} />
            </Col>
            <Col span={6}>
              <Statistic title={tp('questioning.glossaries.statsUser')} value={glossaries.filter(g => g.category === tp('questioning.glossaries.categoryUser')).length} />
            </Col>
            <Col span={6}>
              <Statistic title={tp('questioning.glossaries.statsOther')} value={glossaries.filter(g => g.category !== tp('questioning.glossaries.categorySales') && g.category !== tp('questioning.glossaries.categoryUser')).length} />
            </Col>
          </Row>
          <Alert
            message={tp('questioning.glossaries.alertMessage')}
            description={tp('questioning.glossaries.alertDescription')}
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <Table
            columns={glossaryColumns}
            dataSource={glossaries}
            rowKey="id"
            pagination={false}
          />
        </Card>
      ),
    },
    {
      key: 'test',
      label: (
        <span>
          <PlayCircleOutlined />
          {tp('questioning.tabs.ask')}
        </span>
      ),
      children: (
        <Card title={tp('questioning.ask.title')}>
          <Space direction="vertical" style={{ width: '100%' }} size="large">
            <Card size="small">
              <Search
                placeholder={tp('questioning.ask.questionPlaceholder')}
                enterButton={tp('questioning.ask.askButton')}
                size="large"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                onSearch={handleTestQuestion}
                loading={testing}
              />
              <div style={{ marginTop: 12 }}>
                <Space>
                  <span>{tp('questioning.ask.exampleLabel')}：</span>
                  <Tag
                    style={{ cursor: 'pointer' }}
                    onClick={() => setQuestion(tp('questioning.ask.example1'))}
                  >
                    {tp('questioning.ask.example1')}
                  </Tag>
                  <Tag
                    style={{ cursor: 'pointer' }}
                    onClick={() => setQuestion(tp('questioning.ask.example2'))}
                  >
                    {tp('questioning.ask.example2')}
                  </Tag>
                  <Tag
                    style={{ cursor: 'pointer' }}
                    onClick={() => setQuestion(tp('questioning.ask.example3'))}
                  >
                    {tp('questioning.ask.example3')}
                  </Tag>
                  <Tag
                    style={{ cursor: 'pointer' }}
                    onClick={() => setQuestion(tp('questioning.ask.example4'))}
                  >
                    {tp('questioning.ask.example4')}
                  </Tag>
                </Space>
              </div>
            </Card>

            {testResult && (
              <Card size="small" title={tp('questioning.ask.resultTitle')}>
                <Descriptions column={1} bordered size="small">
                  <Descriptions.Item label={tp('questioning.ask.confidence')}>
                    <Progress percent={Math.round(testResult.confidence * 100)} status="active" />
                  </Descriptions.Item>
                  <Descriptions.Item label={tp('questioning.ask.recognizedTerms')}>
                    {testResult.glossaries.map((g: string) => (
                      <Tag key={g} color="purple">{g}</Tag>
                    ))}
                  </Descriptions.Item>
                  <Descriptions.Item label={tp('questioning.ask.explanation')}>
                    {testResult.explanation}
                  </Descriptions.Item>
                  <Descriptions.Item label={tp('questioning.ask.generatedSQL')}>
                    <pre style={{
                      background: '#f5f5f5',
                      padding: '12px',
                      borderRadius: '4px',
                      overflow: 'auto',
                      maxHeight: '300px'
                    }}>
                      {testResult.sql}
                    </pre>
                  </Descriptions.Item>
                </Descriptions>
                <div style={{ marginTop: 16 }}>
                  <Space>
                    <Button type="primary" icon={<PlayCircleOutlined />}>
                      {tp('questioning.ask.executeButton')}
                    </Button>
                    <Button onClick={() => setTestResult(null)}>
                      {tp('questioning.ask.clearButton')}
                    </Button>
                  </Space>
                </div>
              </Card>
            )}
          </Space>
        </Card>
      ),
    },
    {
      key: 'history',
      label: (
        <span>
          <HistoryOutlined />
          {tp('questioning.tabs.history')}
        </span>
      ),
      children: (
        <Card title={tp('questioning.history.title')}>
          <Alert
            message={tp('questioning.history.alertMessage')}
            description={tp('questioning.history.alertDescription')}
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <Table
            columns={historyColumns}
            dataSource={histories}
            rowKey="id"
            pagination={{
              total: histories.length,
              pageSize: 10,
              showSizeChanger: true,
              showQuickJumper: true,
            }}
          />
        </Card>
      ),
    },
  ];

  return (
    <div>
      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        items={tabItems}
        size="large"
      />

      {/* 数据库编辑弹窗 */}
      <Modal
        title={editingDb ? tp('questioning.databases.editModalTitle') : tp('questioning.databases.addModalTitle')}
        open={dbModalVisible}
        onOk={handleSubmitDb}
        onCancel={() => {
          setDbModalVisible(false);
          dbForm.resetFields();
        }}
        width={600}
        okText={tp('common.confirm')}
        cancelText={tp('common.cancel')}
      >
        <Form form={dbForm} layout="vertical">
          <Form.Item
            label={tp('questioning.databases.nameLabel')}
            name="name"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.databases.nameLabel') }) }]}
          >
            <Input placeholder={tp('questioning.databases.nameLabel')} />
          </Form.Item>

          <Row gutter={16}>
            <Col span={12}>
              <Form.Item
                label={tp('questioning.databases.typeLabel')}
                name="type"
                initialValue="MySQL"
                rules={[{ required: true, message: tp('common.validation.requiredSelect', { field: tp('questioning.databases.typeLabel') }) }]}
              >
                <Select placeholder={tp('questioning.databases.typeLabel')}>
                  <Select.Option value="MySQL">{tp('questioning.databases.typeMySQL')}</Select.Option>
                  <Select.Option value="PostgreSQL">{tp('questioning.databases.typePostgreSQL')}</Select.Option>
                  <Select.Option value="Oracle">{tp('questioning.databases.typeOracle')}</Select.Option>
                  <Select.Option value="SQLServer">{tp('questioning.databases.typeSQLServer')}</Select.Option>
                </Select>
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item
                label={tp('questioning.databases.portLabel')}
                name="port"
                initialValue={3306}
                rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.databases.portLabel') }) }]}
              >
                <Input type="number" placeholder={tp('questioning.databases.portLabel')} />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item
            label={tp('questioning.databases.hostLabel')}
            name="host"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.databases.hostLabel') }) }]}
          >
            <Input placeholder={tp('questioning.databases.hostPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.databases.databaseLabel')}
            name="database"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.databases.databaseLabel') }) }]}
          >
            <Input placeholder={tp('questioning.databases.databaseLabel')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.databases.usernameLabel')}
            name="username"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.databases.usernameLabel') }) }]}
          >
            <Input placeholder={tp('questioning.databases.usernameLabel')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.databases.passwordLabel')}
            name="password"
          >
            <Input.Password placeholder={tp('questioning.databases.passwordLabel')} />
          </Form.Item>
        </Form>
      </Modal>

      {/* 术语编辑弹窗 */}
      <Modal
        title={tp('questioning.glossaries.addModalTitle')}
        open={glossaryModalVisible}
        onOk={handleSubmitGlossary}
        onCancel={() => {
          setGlossaryModalVisible(false);
          glossaryForm.resetFields();
        }}
        width={600}
        okText={tp('common.confirm')}
        cancelText={tp('common.cancel')}
      >
        <Form form={glossaryForm} layout="vertical">
          <Form.Item
            label={tp('questioning.glossaries.termLabel')}
            name="term"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.glossaries.termLabel') }) }]}
          >
            <Input placeholder={tp('questioning.glossaries.termPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.glossaries.definitionLabel')}
            name="definition"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('questioning.glossaries.definitionLabel') }) }]}
          >
            <Input placeholder={tp('questioning.glossaries.definitionPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.glossaries.mappingLabel')}
            name="mapping"
            rules={[{ required: true, message: tp('questioning.glossaries.mappingRequired') }]}
          >
            <TextArea rows={3} placeholder={tp('questioning.glossaries.mappingPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('questioning.glossaries.categoryLabel')}
            name="category"
            initialValue={tp('questioning.glossaries.categorySales')}
            rules={[{ required: true, message: tp('common.validation.requiredSelect', { field: tp('questioning.glossaries.categoryLabel') }) }]}
          >
            <Select placeholder={tp('questioning.glossaries.categoryPlaceholder')}>
              <Select.Option value={tp('questioning.glossaries.categorySales')}>{tp('questioning.glossaries.categorySales')}</Select.Option>
              <Select.Option value={tp('questioning.glossaries.categoryUser')}>{tp('questioning.glossaries.categoryUser')}</Select.Option>
              <Select.Option value={tp('questioning.glossaries.categoryProduct')}>{tp('questioning.glossaries.categoryProduct')}</Select.Option>
              <Select.Option value={tp('questioning.glossaries.categoryFinance')}>{tp('questioning.glossaries.categoryFinance')}</Select.Option>
            </Select>
          </Form.Item>

          <Form.Item
            label={tp('questioning.glossaries.exampleLabel')}
            name="example"
            rules={[{ required: true, message: tp('questioning.glossaries.exampleRequired') }]}
          >
            <Input placeholder={tp('questioning.glossaries.examplePlaceholder')} />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default QuestioningPage;
