// frontend-vue/src/views/Users.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Edit, Delete, Refresh, User as UserIcon, Search } from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'
import type { User, UserCreate, UserUpdate } from '../types'
import { userApi } from '../services/api'

const { t } = useI18n()

// State
const loading = ref(false)
const users = ref<User[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = ref(10)
const searchQuery = ref('')
const roleFilter = ref<string>()
const statusFilter = ref<string>()

const modalVisible = ref(false)
const editingUser = ref<User | null>(null)
const formData = ref({
  username: '',
  email: '',
  role: 'user' as 'admin' | 'user' | 'readonly',
  status: 'active' as 'active' | 'inactive'
})

// Fetch users
const fetchUsers = async () => {
  try {
    loading.value = true
    const response = await userApi.getUsers({
      skip: (page.value - 1) * pageSize.value,
      limit: pageSize.value,
      search: searchQuery.value || undefined,
      role: roleFilter.value,
      status: statusFilter.value,
    })
    users.value = response.users || []
    total.value = response.total || 0
  } catch (error) {
    ElMessage.error(t('users.fetchFailed'))
  } finally {
    loading.value = false
  }
}

// Watch for changes
watch([page, pageSize, searchQuery, roleFilter, statusFilter], () => {
  fetchUsers()
})

// Handle add
const handleAdd = () => {
  editingUser.value = null
  formData.value = {
    username: '',
    email: '',
    role: 'user',
    status: 'active'
  }
  modalVisible.value = true
}

// Handle edit
const handleEdit = (record: User) => {
  editingUser.value = record
  formData.value = {
    username: record.username,
    email: record.email,
    role: record.role,
    status: record.status
  }
  modalVisible.value = true
}

// Handle delete
const handleDelete = async (id: string) => {
  try {
    await ElMessageBox.confirm(
      t('users.deleteConfirm'),
      'Warning',
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning',
      }
    )
    await userApi.deleteUser(id)
    ElMessage.success(t('users.deleteSuccess'))
    fetchUsers()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('users.deleteFailed'))
    }
  }
}

// Handle submit
const handleSubmit = async () => {
  try {
    if (editingUser.value) {
      const updateData: UserUpdate = {
        username: formData.value.username,
        email: formData.value.email,
        role: formData.value.role,
        status: formData.value.status,
      }
      await userApi.updateUser(editingUser.value.id, updateData)
      ElMessage.success(t('users.updateSuccess'))
    } else {
      const createData: UserCreate = {
        username: formData.value.username,
        email: formData.value.email,
        role: formData.value.role,
      }
      await userApi.createUser(createData)
      ElMessage.success(t('users.createSuccess'))

      // Clear filters and reset to first page
      searchQuery.value = ''
      roleFilter.value = undefined
      statusFilter.value = undefined
      page.value = 1
    }

    modalVisible.value = false

    // Refresh data
    setTimeout(() => {
      fetchUsers()
    }, 100)
  } catch (error) {
    ElMessage.error(editingUser.value ? t('users.updateFailed') : t('users.createFailed'))
  }
}

// Helper functions
const getRoleType = (role: string) => {
  switch (role) {
    case 'admin':
      return 'danger'
    case 'user':
      return 'primary'
    case 'readonly':
      return 'info'
    default:
      return 'info'
  }
}

const getRoleText = (role: string) => {
  switch (role) {
    case 'admin':
      return t('users.roleAdmin')
    case 'user':
      return t('users.roleUser')
    case 'readonly':
      return t('users.roleReadonly')
    default:
      return role
  }
}

const getStatusType = (status: string) => {
  return status === 'active' ? 'success' : 'info'
}

const getStatusText = (status: string) => {
  return status === 'active' ? t('users.statusActive') : t('users.statusInactive')
}

const formatDate = (date: string) => {
  return date ? new Date(date).toLocaleString('zh-CN') : '-'
}

// Statistics
const adminCount = computed(() => users.value.filter((u) => u.role === 'admin').length)
const activeUserCount = computed(() => users.value.filter((u) => u.status === 'active').length)
const regularUserCount = computed(() => users.value.filter((u) => u.role === 'user').length)

// Load data on mount
onMounted(() => {
  fetchUsers()
})
</script>

<template>
  <div class="page-container">
    <!-- Statistics Cards -->
    <el-card class="stats-card mb-16">
      <el-row :gutter="16">
        <el-col :span="6">
          <el-statistic :title="t('users.statsTotal')" :value="total">
            <template #prefix>
              <el-icon :size="20"><UserIcon /></el-icon>
            </template>
          </el-statistic>
        </el-col>
        <el-col :span="6">
          <el-statistic :title="t('users.statsActive')" :value="activeUserCount">
            <template #suffix>/ {{ total }}</template>
          </el-statistic>
        </el-col>
        <el-col :span="6">
          <el-statistic :title="t('users.statsAdmin')" :value="adminCount" />
        </el-col>
        <el-col :span="6">
          <el-statistic :title="t('users.statsUser')" :value="regularUserCount" />
        </el-col>
      </el-row>
    </el-card>

    <!-- User List Card -->
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ t('users.title') }}</span>
          <div class="header-actions">
            <el-button :icon="Refresh" @click="fetchUsers">
              {{ t('common.refresh') }}
            </el-button>
            <el-button type="primary" :icon="Plus" @click="handleAdd">
              {{ t('users.addButton') }}
            </el-button>
          </div>
        </div>
      </template>

      <!-- Filters -->
      <div class="filters mb-16">
        <el-input
          v-model="searchQuery"
          :placeholder="t('users.searchPlaceholder')"
          clearable
          style="width: 300px; margin-right: 12px"
          @keyup.enter="fetchUsers"
        >
          <template #append>
            <el-button :icon="Search" @click="fetchUsers" />
          </template>
        </el-input>

        <el-select
          v-model="roleFilter"
          :placeholder="t('users.roleFilter')"
          clearable
          style="width: 120px; margin-right: 12px"
          @change="fetchUsers"
        >
          <el-option value="admin" :label="t('users.roleAdmin')" />
          <el-option value="user" :label="t('users.roleUser')" />
          <el-option value="readonly" :label="t('users.roleReadonly')" />
        </el-select>

        <el-select
          v-model="statusFilter"
          :placeholder="t('users.statusFilter')"
          clearable
          style="width: 120px"
          @change="fetchUsers"
        >
          <el-option value="active" :label="t('users.statusActive')" />
          <el-option value="inactive" :label="t('users.statusInactive')" />
        </el-select>
      </div>

      <!-- Table -->
      <el-table
        v-loading="loading"
        :data="users"
        stripe
        style="width: 100%"
      >
        <el-table-column prop="username" :label="t('users.username')" min-width="110" header-align="center" />
        <el-table-column prop="email" :label="t('users.email')" min-width="180" header-align="center" />
        <el-table-column :label="t('users.role')" width="90" header-align="center">
          <template #default="{ row }">
            <el-tag :type="getRoleType(row.role)">
              {{ getRoleText(row.role) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="t('users.status')" width="90" header-align="center">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)">
              {{ getStatusText(row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="t('users.createTime')" width="170" header-align="center">
          <template #default="{ row }">
            {{ formatDate(row.created_at) }}
          </template>
        </el-table-column>
        <el-table-column :label="t('users.lastLogin')" width="170" header-align="center">
          <template #default="{ row }">
            {{ formatDate(row.last_login) }}
          </template>
        </el-table-column>
        <el-table-column :label="t('common.actions')" width="150" fixed="right" header-align="center">
          <template #default="{ row }">
            <el-button
              type="primary"
              size="small"
              :icon="Edit"
              link
              @click="handleEdit(row)"
            >
              {{ t('common.edit') }}
            </el-button>
            <el-button
              type="danger"
              size="small"
              :icon="Delete"
              link
              @click="handleDelete(row.id)"
            >
              {{ t('common.delete') }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <!-- Pagination -->
      <el-pagination
        v-model:current-page="page"
        v-model:page-size="pageSize"
        :page-sizes="[10, 20, 50, 100]"
        :total="total"
        layout="total, sizes, prev, pager, next, jumper"
        class="mt-24"
      />
    </el-card>

    <!-- Add/Edit Modal -->
    <el-dialog
      v-model="modalVisible"
      :title="editingUser ? t('users.editModalTitle') : t('users.addModalTitle')"
      width="500px"
    >
      <el-form :model="formData" label-width="100px">
        <el-form-item :label="t('users.usernameLabel')" required>
          <el-input
            v-model="formData.username"
            :placeholder="t('users.usernamePlaceholder')"
          />
        </el-form-item>

        <el-form-item :label="t('users.emailLabel')" required>
          <el-input
            v-model="formData.email"
            :placeholder="t('users.emailPlaceholder')"
          />
        </el-form-item>

        <el-form-item :label="t('users.roleLabel')" required>
          <el-select
            v-model="formData.role"
            :placeholder="t('users.rolePlaceholder')"
            style="width: 100%"
          >
            <el-option value="admin" :label="t('users.roleAdmin')" />
            <el-option value="user" :label="t('users.roleUser')" />
            <el-option value="readonly" :label="t('users.roleReadonly')" />
          </el-select>
        </el-form-item>

        <el-form-item v-if="editingUser" :label="t('users.statusLabel')" required>
          <el-select
            v-model="formData.status"
            :placeholder="t('users.statusPlaceholder')"
            style="width: 100%"
          >
            <el-option value="active" :label="t('users.statusActive')" />
            <el-option value="inactive" :label="t('users.statusInactive')" />
          </el-select>
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="modalVisible = false">
          {{ t('common.cancel') }}
        </el-button>
        <el-button type="primary" @click="handleSubmit">
          {{ t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  gap: 8px;
}

.filters {
  display: flex;
  align-items: center;
}
</style>

// frontend/src/pages/Users.tsx
import React, { useEffect, useState, useMemo } from 'react';
import {
  Table,
  Button,
  Space,
  Modal,
  Form,
  Input,
  Select,
  Tag,
  message,
  Popconfirm,
  Card,
  Row,
  Col,
  Statistic,
} from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  ReloadOutlined,
  UserOutlined,
} from '@ant-design/icons';
import type { User, UserCreate, UserUpdate } from '../types';
import { userApi } from '../services/api';
import { useTranslation } from '../contexts/LanguageContext';
import { createTranslateProxy } from '../utils/i18n';

const { Search } = Input;

const Users: React.FC = () => {
  const { t } = useTranslation();
  const tp = useMemo(() => createTranslateProxy(t), [t]);
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<User[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [searchQuery, setSearchQuery] = useState('');
  const [roleFilter, setRoleFilter] = useState<string | undefined>();
  const [statusFilter, setStatusFilter] = useState<string | undefined>();

  const [modalVisible, setModalVisible] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [form] = Form.useForm();

  useEffect(() => {
    fetchUsers();
  }, [page, pageSize, searchQuery, roleFilter, statusFilter]);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const response = await userApi.getUsers({
        skip: (page - 1) * pageSize,
        limit: pageSize,
        search: searchQuery || undefined,
        role: roleFilter,
        status: statusFilter,
      });
      setUsers(response.users || []);
      setTotal(response.total || 0);
    } catch (error) {
      message.error(tp('users.fetchFailed'));
    } finally {
      setLoading(false);
    }
  };

  const handleAdd = () => {
    setEditingUser(null);
    form.resetFields();
    form.setFieldsValue({ role: 'user', status: 'active' });
    setModalVisible(true);
  };

  const handleEdit = (record: User) => {
    setEditingUser(record);
    form.setFieldsValue(record);
    setModalVisible(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await userApi.deleteUser(id);
      message.success(tp('users.deleteSuccess'));
      fetchUsers();
    } catch (error) {
      message.error(tp('users.deleteFailed'));
    }
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      if (editingUser) {
        const updateData: UserUpdate = {
          username: values.username,
          email: values.email,
          role: values.role,
          status: values.status,
        };
        await userApi.updateUser(editingUser.id, updateData);
        message.success(tp('users.updateSuccess'));
      } else {
        const createData: UserCreate = {
          username: values.username,
          email: values.email,
          role: values.role,
        };
        await userApi.createUser(createData);
        message.success(tp('users.createSuccess'));

        // 创建成功后，清除筛选条件并跳转到第一页
        setSearchQuery('');
        setRoleFilter(undefined);
        setStatusFilter(undefined);
        setPage(1);
      }

      setModalVisible(false);
      form.resetFields();

      // 延迟一下再刷新，确保后端数据已保存
      setTimeout(() => {
        fetchUsers();
      }, 100);
    } catch (error) {
      message.error(editingUser ? tp('users.updateFailed') : tp('users.createFailed'));
    }
  };

  const getRoleColor = (role: string) => {
    switch (role) {
      case 'admin':
        return 'red';
      case 'user':
        return 'blue';
      case 'readonly':
        return 'default';
      default:
        return 'default';
    }
  };

  const getRoleText = (role: string) => {
    switch (role) {
      case 'admin':
        return tp('users.roleAdmin');
      case 'user':
        return tp('users.roleUser');
      case 'readonly':
        return tp('users.roleReadonly');
      default:
        return role;
    }
  };

  const getStatusColor = (status: string) => {
    return status === 'active' ? 'success' : 'default';
  };

  const getStatusText = (status: string) => {
    return status === 'active' ? tp('users.statusActive') : tp('users.statusInactive');
  };

  const columns = [
    {
      title: tp('users.username'),
      dataIndex: 'username',
      key: 'username',
      width: 120,
      align: 'center' as const,
    },
    {
      title: tp('users.email'),
      dataIndex: 'email',
      key: 'email',
      width: 200,
      align: 'center' as const,
    },
    {
      title: tp('users.role'),
      dataIndex: 'role',
      key: 'role',
      width: 100,
      align: 'center' as const,
      render: (role: string) => <Tag color={getRoleColor(role)}>{getRoleText(role)}</Tag>,
    },
    {
      title: tp('users.status'),
      dataIndex: 'status',
      key: 'status',
      width: 100,
      align: 'center' as const,
      render: (status: string) => <Tag color={getStatusColor(status)}>{getStatusText(status)}</Tag>,
    },
    {
      title: tp('users.createTime'),
      dataIndex: 'created_at',
      key: 'created_at',
      width: 180,
      align: 'center' as const,
      render: (date: string) => new Date(date).toLocaleString('zh-CN'),
    },
    {
      title: tp('users.lastLogin'),
      dataIndex: 'last_login',
      key: 'last_login',
      width: 180,
      align: 'center' as const,
      render: (date: string) => (date ? new Date(date).toLocaleString('zh-CN') : '-'),
    },
    {
      title: tp('common.actions'),
      key: 'action',
      width: 150,
      fixed: 'right' as const,
      align: 'center' as const,
      render: (_: any, record: User) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            {tp('common.edit')}
          </Button>
          <Popconfirm
            title={tp('users.deleteConfirm')}
            onConfirm={() => handleDelete(record.id)}
            okText={tp('common.confirm')}
            cancelText={tp('common.cancel')}
          >
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>
              {tp('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // Calculate statistics
  const adminCount = users.filter((u) => u.role === 'admin').length;
  const activeUserCount = users.filter((u) => u.status === 'active').length;

  return (
    <div>
      <Card style={{ marginBottom: 16 }}>
        <Row gutter={16}>
          <Col span={6}>
            <Statistic title={tp('users.statsTotal')} value={total} prefix={<UserOutlined />} />
          </Col>
          <Col span={6}>
            <Statistic title={tp('users.statsActive')} value={activeUserCount} suffix={`/ ${total}`} />
          </Col>
          <Col span={6}>
            <Statistic title={tp('users.statsAdmin')} value={adminCount} />
          </Col>
          <Col span={6}>
            <Statistic title={tp('users.statsUser')} value={users.filter((u) => u.role === 'user').length} />
          </Col>
        </Row>
      </Card>

      <Card
        title={tp('users.title')}
        extra={
          <Space>
            <Button icon={<ReloadOutlined />} onClick={fetchUsers}>
              {tp('common.refresh')}
            </Button>
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
              {tp('users.addButton')}
            </Button>
          </Space>
        }
      >
        <Space style={{ marginBottom: 16 }} size="middle">
          <Search
            placeholder={tp('users.searchPlaceholder')}
            allowClear
            style={{ width: 300 }}
            onSearch={setSearchQuery}
            enterButton
          />
          <Select
            placeholder={tp('users.roleFilter')}
            allowClear
            style={{ width: 120 }}
            value={roleFilter}
            onChange={setRoleFilter}
          >
            <Select.Option value="admin">{tp('users.roleAdmin')}</Select.Option>
            <Select.Option value="user">{tp('users.roleUser')}</Select.Option>
            <Select.Option value="readonly">{tp('users.roleReadonly')}</Select.Option>
          </Select>
          <Select
            placeholder={tp('users.statusFilter')}
            allowClear
            style={{ width: 120 }}
            value={statusFilter}
            onChange={setStatusFilter}
          >
            <Select.Option value="active">{tp('users.statusActive')}</Select.Option>
            <Select.Option value="inactive">{tp('users.statusInactive')}</Select.Option>
          </Select>
        </Space>

        <Table
          columns={columns}
          dataSource={users}
          rowKey="id"
          loading={loading}
          scroll={{ x: 1200 }}
          pagination={{
            current: page,
            pageSize: pageSize,
            total: total,
            showSizeChanger: true,
            showTotal: (total) => tp('common.pagination.total', { total }),
            onChange: (page, pageSize) => {
              setPage(page);
              setPageSize(pageSize);
            },
          }}
        />
      </Card>

      <Modal
        title={editingUser ? tp('users.editModalTitle') : tp('users.addModalTitle')}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => {
          setModalVisible(false);
          form.resetFields();
        }}
        okText={tp('common.confirm')}
        cancelText={tp('common.cancel')}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            label={tp('users.usernameLabel')}
            name="username"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('users.usernameLabel') }) }]}
          >
            <Input placeholder={tp('users.usernamePlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('users.emailLabel')}
            name="email"
            rules={[
              { required: true, message: tp('common.validation.required', { field: tp('users.emailLabel') }) },
              { type: 'email', message: tp('common.validation.email') },
            ]}
          >
            <Input placeholder={tp('users.emailPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('users.roleLabel')}
            name="role"
            rules={[{ required: true, message: tp('common.validation.requiredSelect', { field: tp('users.roleLabel') }) }]}
          >
            <Select placeholder={tp('users.rolePlaceholder')}>
              <Select.Option value="admin">{tp('users.roleAdmin')}</Select.Option>
              <Select.Option value="user">{tp('users.roleUser')}</Select.Option>
              <Select.Option value="readonly">{tp('users.roleReadonly')}</Select.Option>
            </Select>
          </Form.Item>

          {editingUser && (
            <Form.Item
              label={tp('users.statusLabel')}
              name="status"
              rules={[{ required: true, message: tp('common.validation.requiredSelect', { field: tp('users.statusLabel') }) }]}
            >
              <Select placeholder={tp('users.statusPlaceholder')}>
                <Select.Option value="active">{tp('users.statusActive')}</Select.Option>
                <Select.Option value="inactive">{tp('users.statusInactive')}</Select.Option>
              </Select>
            </Form.Item>
          )}
        </Form>
      </Modal>
    </div>
  );
};

export default Users;
