// frontend/src/pages/Knowledge.tsx
import React, { useEffect, useState } from 'react';
import {
  Table,
  Button,
  Space,
  Modal,
  Form,
  Input,
  Select,
  AutoComplete,
  Tag,
  message,
  Popconfirm,
  Card,
  Row,
  Col,
  Statistic,
  Divider,
  Tabs,
  Descriptions,
  Alert,
} from 'antd';
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SearchOutlined,
  ReloadOutlined,
  ImportOutlined,
  ExportOutlined,
  FolderOutlined,
  FileOutlined,
  InfoCircleOutlined,
  LinkOutlined,
} from '@ant-design/icons';
import type { KnowledgeDocument, SearchResult } from '../types';
import { knowledgeApi } from '../services/api';
import { useTranslation } from '../contexts/LanguageContext';
import { createTranslateProxy } from '../utils/i18n';

const { TextArea } = Input;
const { Search } = Input;

const Knowledge: React.FC = () => {
  const { t } = useTranslation();
  const tp = createTranslateProxy(t);
  const [activeTab, setActiveTab] = useState('files');

  // 文件管理状态
  const [loading, setLoading] = useState(false);
  const [documents, setDocuments] = useState<KnowledgeDocument[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string | undefined>();

  const [modalVisible, setModalVisible] = useState(false);
  const [editingDoc, setEditingDoc] = useState<KnowledgeDocument | null>(null);
  const [form] = Form.useForm();

  const [searchModalVisible, setSearchModalVisible] = useState(false);
  const [searchQueryText, setSearchQueryText] = useState('');
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const [searchLoading, setSearchLoading] = useState(false);

  // 目录映射状态
  const [mappings, setMappings] = useState<any[]>([]);
  const [mappingModalVisible, setMappingModalVisible] = useState(false);
  const [mappingForm] = Form.useForm();

  useEffect(() => {
    if (activeTab === 'files') {
      fetchDocuments();
      fetchCategories();
    } else if (activeTab === 'mappings') {
      fetchMappings();
    }
  }, [activeTab, page, pageSize, searchQuery, selectedCategory]);

  // ==================== 文件管理 ====================
  const fetchDocuments = async () => {
    try {
      setLoading(true);
      const response = await knowledgeApi.getDocuments({
        skip: (page - 1) * pageSize,
        limit: pageSize,
        category: selectedCategory,
        search: searchQuery || undefined,
      });
      setDocuments(response.documents || []);
      setTotal(response.total || 0);
    } catch (error) {
      message.error(tp('knowledge.files.fetchFailed'));
    } finally {
      setLoading(false);
    }
  };

  const fetchCategories = async () => {
    try {
      const response = await knowledgeApi.getCategories();
      setCategories(response.categories || []);
    } catch (error) {
      console.error('Failed to fetch categories:', error);
    }
  };

  const handleAdd = () => {
    setEditingDoc(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (record: KnowledgeDocument) => {
    setEditingDoc(record);
    form.setFieldsValue(record);
    setModalVisible(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await knowledgeApi.deleteDocument(id);
      message.success(tp('knowledge.files.deleteSuccess'));
      fetchDocuments();
    } catch (error) {
      message.error(tp('knowledge.files.deleteFailed'));
    }
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      if (editingDoc) {
        await knowledgeApi.updateDocument(editingDoc.id, values);
        message.success(tp('knowledge.files.updateSuccess'));
      } else {
        await knowledgeApi.createDocument(values);
        message.success(tp('knowledge.files.createSuccess'));
      }

      setModalVisible(false);
      form.resetFields();
      fetchDocuments();
      fetchCategories();
    } catch (error) {
      message.error(editingDoc ? tp('knowledge.files.updateFailed') : tp('knowledge.files.createFailed'));
    }
  };

  const handleSemanticSearch = async () => {
    if (!searchQueryText.trim()) {
      message.warning(tp('knowledge.files.searchWarning'));
      return;
    }

    try {
      setSearchLoading(true);
      const response = await knowledgeApi.semanticSearch(searchQueryText, 5, selectedCategory);
      setSearchResults(response.results || []);
    } catch (error) {
      message.error(tp('knowledge.files.searchFailed'));
    } finally {
      setSearchLoading(false);
    }
  };

  const handleRebuildVectors = async () => {
    try {
      setLoading(true);
      const response = await knowledgeApi.rebuildVectors();
      message.success(tp('knowledge.files.rebuildSuccess', {
        vectorized: response.vectorized,
        total: response.total,
      }));
      fetchDocuments();
    } catch (error) {
      message.error(tp('knowledge.files.rebuildFailed') || '重建失败');
    } finally {
      setLoading(false);
    }
  };

  const documentColumns = [
    {
      title: tp('knowledge.files.colTitle'),
      dataIndex: 'title',
      key: 'title',
      width: 200,
      ellipsis: true,
    },
    {
      title: tp('knowledge.files.colCategory'),
      dataIndex: 'category',
      key: 'category',
      width: 120,
      render: (category: string) => <Tag color="blue">{category}</Tag>,
    },
    {
      title: tp('knowledge.files.colTags'),
      dataIndex: 'tags',
      key: 'tags',
      width: 150,
      render: (tags: string[]) => (
        <>
          {tags?.map((tag) => (
            <Tag key={tag} color="green">
              {tag}
            </Tag>
          ))}
        </>
      ),
    },
    {
      title: tp('knowledge.files.colVectorized'),
      dataIndex: 'vectorized',
      key: 'vectorized',
      width: 100,
      render: (vectorized: boolean) =>
        vectorized ? <Tag color="success">{tp('knowledge.files.indexed')}</Tag> : <Tag color="warning">{tp('knowledge.files.notIndexed')}</Tag>,
    },
    {
      title: tp('knowledge.files.colUpdateTime'),
      dataIndex: 'updated_at',
      key: 'updated_at',
      width: 180,
      render: (date: string) => new Date(date).toLocaleString('zh-CN'),
    },
    {
      title: tp('common.actions'),
      key: 'action',
      width: 150,
      fixed: 'right' as const,
      render: (_: any, record: KnowledgeDocument) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            {tp('common.edit')}
          </Button>
          <Popconfirm
            title={tp('knowledge.files.deleteConfirm')}
            onConfirm={() => handleDelete(record.id)}
            okText={tp('common.confirm')}
            cancelText={tp('common.cancel')}
          >
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>
              {tp('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ==================== 目录映射 ====================
  const fetchMappings = async () => {
    try {
      const response = await knowledgeApi.getMappings();
      setMappings(response.mappings || []);
    } catch (error) {
      message.error(tp('knowledge.mappings.fetchFailed'));
    }
  };

  const handleAddMapping = () => {
    mappingForm.resetFields();
    setMappingModalVisible(true);
  };

  const handleDeleteMapping = async (id: string) => {
    try {
      await knowledgeApi.deleteMapping(id);
      message.success(tp('knowledge.mappings.deleteSuccess'));
      fetchMappings();
    } catch (error) {
      message.error(tp('knowledge.mappings.deleteFailed'));
    }
  };

  const handleExecuteMapping = (id: string) => {
    message.success(tp('knowledge.mappings.executeSuccess', { id }));
  };

  const handleViewMappingDetail = (record: any) => {
    Modal.info({
      title: tp('knowledge.mappings.detailTitle'),
      width: 600,
      content: (
        <div>
          <p><strong>{tp('knowledge.mappings.taskId')}：</strong>{record.id}</p>
          <p><strong>{tp('knowledge.mappings.directoryName')}：</strong>{record.directory_name}</p>
          <p><strong>{tp('knowledge.mappings.directoryPath')}：</strong>{record.directory_path}</p>
          <p><strong>{tp('knowledge.mappings.fileSystem')}：</strong>{record.file_system}</p>
          <p><strong>{tp('knowledge.mappings.lastImportTime')}：</strong>{record.last_import_time}</p>
          <p><strong>{tp('knowledge.mappings.operator')}：</strong>{record.operator}</p>
        </div>
      ),
    });
  };

  const mappingColumns = [
    {
      title: tp('knowledge.mappings.taskId'),
      dataIndex: 'id',
      key: 'id',
      width: 120,
      render: (id: string) => <Tag color="blue">{id}</Tag>,
    },
    {
      title: tp('knowledge.mappings.directoryName'),
      dataIndex: 'directory_name',
      key: 'directory_name',
      width: 150,
    },
    {
      title: tp('knowledge.mappings.directoryPath'),
      dataIndex: 'directory_path',
      key: 'directory_path',
      width: 200,
      ellipsis: true,
    },
    {
      title: tp('knowledge.mappings.fileSystem'),
      dataIndex: 'file_system',
      key: 'file_system',
      width: 100,
      render: (fs: string) => {
        const colors: Record<string, string> = {
          'NFS': 'blue',
          'S3': 'green',
          'LOCAL': 'orange',
        };
        return <Tag color={colors[fs] || 'default'}>{fs}</Tag>;
      },
    },
    {
      title: tp('knowledge.mappings.lastImportTime'),
      dataIndex: 'last_import_time',
      key: 'last_import_time',
      width: 180,
    },
    {
      title: tp('knowledge.mappings.operator'),
      dataIndex: 'operator',
      key: 'operator',
      width: 120,
      render: (operator: string) => (
        <Space>
          <span>{operator}</span>
        </Space>
      ),
    },
    {
      title: tp('knowledge.mappings.actions'),
      key: 'action',
      width: 180,
      fixed: 'right' as const,
      render: (_: any, record: any) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<SearchOutlined />}
            onClick={() => handleViewMappingDetail(record)}
          >
            {tp('knowledge.mappings.view')}
          </Button>
          <Button
            type="link"
            size="small"
            icon={<ReloadOutlined />}
            onClick={() => handleExecuteMapping(record.id)}
          >
            {tp('knowledge.mappings.execute')}
          </Button>
          <Popconfirm
            title={tp('knowledge.mappings.deleteConfirm')}
            onConfirm={() => handleDeleteMapping(record.id)}
            okText={tp('common.confirm')}
            cancelText={tp('common.cancel')}
          >
            <Button type="link" size="small" danger icon={<DeleteOutlined />}>
              {tp('common.delete')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  // ==================== 渲染 ====================
  const tabItems = [
    {
      key: 'intro',
      label: (
        <span>
          <InfoCircleOutlined />
          {tp('knowledge.tabs.intro')}
        </span>
      ),
      children: (
        <Card>
          <Descriptions title={tp('knowledge.intro.info')} bordered column={2}>
            <Descriptions.Item label={tp('knowledge.intro.name')}>{tp('knowledge.intro.nameValue')}</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.createTime')}>2026-03-01</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.totalDocs')}>{total}</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.indexedDocs')}>{documents.filter(d => d.vectorized).length}</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.categoryCount')}>{categories.length}</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.vectorDimension')}>10</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.storagePath')}>/data/knowledge</Descriptions.Item>
            <Descriptions.Item label={tp('knowledge.intro.indexStatus')}>
              <Tag color="success">{tp('knowledge.intro.indexStatusNormal')}</Tag>
            </Descriptions.Item>
          </Descriptions>

          <Divider />

          <Alert
            message={tp('knowledge.intro.description')}
            description={tp('knowledge.intro.descriptionText')}
            type="info"
            showIcon
          />

          <Divider />

          <Row gutter={16}>
            <Col span={8}>
              <Card>
                <Statistic
                  title={tp('knowledge.intro.statsTotal')}
                  value={total}
                  prefix={<FileOutlined />}
                />
              </Card>
            </Col>
            <Col span={8}>
              <Card>
                <Statistic
                  title={tp('knowledge.intro.statsIndexed')}
                  value={documents.filter(d => d.vectorized).length}
                  suffix={`/ ${total}`}
                  prefix={<SearchOutlined />}
                />
              </Card>
            </Col>
            <Col span={8}>
              <Card>
                <Statistic
                  title={tp('knowledge.intro.statsCategories')}
                  value={categories.length}
                  prefix={<FolderOutlined />}
                />
              </Card>
            </Col>
          </Row>
        </Card>
      ),
    },
    {
      key: 'mappings',
      label: (
        <span>
          <LinkOutlined />
          {tp('knowledge.tabs.mappings')}
        </span>
      ),
      children: (
        <Card
          title={tp('knowledge.mappings.title')}
          extra={
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAddMapping}>
              {tp('knowledge.mappings.addButton')}
            </Button>
          }
        >
          <Alert
            message={tp('knowledge.mappings.description')}
            description={tp('knowledge.mappings.descriptionText')}
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <Table
            columns={mappingColumns}
            dataSource={mappings}
            rowKey="id"
            pagination={false}
          />
        </Card>
      ),
    },
    {
      key: 'files',
      label: (
        <span>
          <FileOutlined />
          {tp('knowledge.tabs.files')}
        </span>
      ),
      children: (
        <>
          <Card style={{ marginBottom: 16 }}>
            <Row gutter={16}>
              <Col span={6}>
                <Statistic title={tp('knowledge.files.statsTotal')} value={total} />
              </Col>
              <Col span={6}>
                <Statistic
                  title={tp('knowledge.files.statsIndexed')}
                  value={documents.filter((d) => d.vectorized).length}
                  suffix={`/ ${total}`}
                />
              </Col>
              <Col span={6}>
                <Statistic title={tp('knowledge.files.statsCategories')} value={categories.length} />
              </Col>
              <Col span={6}>
                <Statistic
                  title={tp('knowledge.files.statsCurrentPage')}
                  value={page}
                  suffix={`/ ${Math.ceil(total / pageSize) || 1}`}
                />
              </Col>
            </Row>
          </Card>

          <Card
            title={tp('knowledge.files.title')}
            extra={
              <Space>
                <Button icon={<ReloadOutlined />} onClick={fetchDocuments}>
                  {tp('common.refresh')}
                </Button>
                <Button icon={<SearchOutlined />} onClick={() => setSearchModalVisible(true)}>
                  {tp('knowledge.files.semanticSearch')}
                </Button>
                <Button icon={<ImportOutlined />}>{tp('common.import')}</Button>
                <Button icon={<ExportOutlined />}>{tp('common.export')}</Button>
                <Popconfirm
                  title={tp('knowledge.files.rebuildConfirm')}
                  onConfirm={handleRebuildVectors}
                  okText={tp('common.confirm')}
                  cancelText={tp('common.cancel')}
                >
                  <Button icon={<ReloadOutlined />}>{tp('knowledge.files.rebuildIndex')}</Button>
                </Popconfirm>
                <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
                  {tp('knowledge.files.addButton')}
                </Button>
              </Space>
            }
          >
            <Space style={{ marginBottom: 16 }} size="middle">
              <Search
                placeholder={tp('knowledge.files.searchPlaceholder')}
                allowClear
                style={{ width: 300 }}
                onSearch={setSearchQuery}
                enterButton
              />
              <Select
                placeholder={tp('knowledge.files.categoryPlaceholder')}
                allowClear
                style={{ width: 150 }}
                value={selectedCategory}
                onChange={setSelectedCategory}
              >
                {categories.map((cat) => (
                  <Select.Option key={cat} value={cat}>
                    {cat}
                  </Select.Option>
                ))}
              </Select>
            </Space>

            <Table
              columns={documentColumns}
              dataSource={documents}
              rowKey="id"
              loading={loading}
              scroll={{ x: 1200 }}
              pagination={{
                current: page,
                pageSize: pageSize,
                total: total,
                showSizeChanger: true,
                showTotal: (total) => tp('common.pagination.total', { total }),
                onChange: (page, pageSize) => {
                  setPage(page);
                  setPageSize(pageSize);
                },
              }}
            />
          </Card>
        </>
      ),
    },
  ];

  return (
    <div>
      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        items={tabItems}
        size="large"
      />

      {/* 文档编辑弹窗 */}
      <Modal
        title={editingDoc ? tp('knowledge.files.editModalTitle') : tp('knowledge.files.addModalTitle')}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => {
          setModalVisible(false);
          form.resetFields();
        }}
        width={800}
        okText={tp('common.confirm')}
        cancelText={tp('common.cancel')}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            label={tp('knowledge.files.titleLabel')}
            name="title"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('knowledge.files.titleLabel') }) }]}
          >
            <Input placeholder={tp('knowledge.files.titlePlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('knowledge.files.categoryLabel')}
            name="category"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('knowledge.files.categoryLabel') }) }]}
            extra={tp('knowledge.files.categoryHelp')}
          >
            <AutoComplete
              options={categories.map((cat) => ({ label: cat, value: cat }))}
              placeholder={tp('knowledge.files.categoryPlaceholder')}
              filterOption={(inputValue, option) =>
                option?.value.toUpperCase().indexOf(inputValue.toUpperCase()) !== -1
              }
            />
          </Form.Item>

          <Form.Item label={tp('knowledge.files.tagsLabel')} name="tags">
            <Select mode="tags" placeholder={tp('knowledge.files.tagsPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('knowledge.files.contentLabel')}
            name="content"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('knowledge.files.contentLabel') }) }]}
          >
            <TextArea rows={10} placeholder={tp('knowledge.files.contentPlaceholder')} />
          </Form.Item>
        </Form>
      </Modal>

      {/* 语义搜索弹窗 */}
      <Modal
        title={tp('knowledge.files.searchModalTitle')}
        open={searchModalVisible}
        onCancel={() => setSearchModalVisible(false)}
        footer={null}
        width={800}
      >
        <Space direction="vertical" style={{ width: '100%' }} size="large">
          <Search
            placeholder={tp('knowledge.files.searchModalPlaceholder')}
            allowClear
            enterButton={tp('common.search')}
            size="large"
            value={searchQueryText}
            onChange={(e) => setSearchQueryText(e.target.value)}
            onSearch={handleSemanticSearch}
            loading={searchLoading}
          />

          {searchResults.length > 0 && (
            <div>
              <Divider>{tp('knowledge.files.searchResults')}</Divider>
              {searchResults.map((result) => (
                <Card
                  key={result.id}
                  size="small"
                  style={{ marginBottom: 8 }}
                  title={
                    <Space>
                      <span>{result.title}</span>
                      <Tag color="blue">{tp('knowledge.files.similarity')}: {(result.similarity_score * 100).toFixed(1)}%</Tag>
                    </Space>
                  }
                >
                  <p>{result.content.substring(0, 200)}...</p>
                </Card>
              ))}
            </div>
          )}
        </Space>
      </Modal>

      {/* 目录映射弹窗 */}
      <Modal
        title={tp('knowledge.mappings.modalTitle')}
        open={mappingModalVisible}
        onOk={async () => {
          try {
            const values = await mappingForm.validateFields();
            await knowledgeApi.createMapping(values);
            message.success(tp('knowledge.mappings.addSuccess'));
            setMappingModalVisible(false);
            mappingForm.resetFields();
            fetchMappings();
          } catch (error) {
            message.error(tp('knowledge.mappings.addFailed'));
          }
        }}
        onCancel={() => {
          setMappingModalVisible(false);
          mappingForm.resetFields();
        }}
        okText={tp('common.confirm')}
        cancelText={tp('common.cancel')}
        width={600}
      >
        <Form form={mappingForm} layout="vertical">
          <Form.Item
            label={tp('knowledge.mappings.directoryNameLabel')}
            name="directoryName"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('knowledge.mappings.directoryNameLabel') }) }]}
          >
            <Input placeholder={tp('knowledge.mappings.directoryNamePlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('knowledge.mappings.directoryPathLabel')}
            name="directoryPath"
            rules={[{ required: true, message: tp('common.validation.required', { field: tp('knowledge.mappings.directoryPathLabel') }) }]}
          >
            <Input placeholder={tp('knowledge.mappings.directoryPathPlaceholder')} />
          </Form.Item>

          <Form.Item
            label={tp('knowledge.mappings.fileSystemLabel')}
            name="fileSystem"
            rules={[{ required: true, message: tp('common.validation.requiredSelect', { field: tp('knowledge.mappings.fileSystemLabel') }) }]}
            initialValue="NFS"
          >
            <Select placeholder={tp('knowledge.mappings.fileSystemPlaceholder')}>
              <Select.Option value="NFS">{tp('knowledge.mappings.fileSystemNFS')}</Select.Option>
              <Select.Option value="S3">{tp('knowledge.mappings.fileSystemS3')}</Select.Option>
              <Select.Option value="LOCAL">{tp('knowledge.mappings.fileSystemLOCAL')}</Select.Option>
            </Select>
          </Form.Item>
        </Form>
      </Modal>

    </div>
  );
};

export default Knowledge;

// frontend-vue/src/views/Knowledge.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  Plus,
  Edit,
  Delete,
  Search,
  Refresh,
  InfoFilled,
  Link
} from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'
import type { KnowledgeDocument, SearchResult, DocumentCreate, DocumentUpdate, DirectoryMapping, MappingCreate } from '../types'
import { knowledgeApi } from '../services/api'

const { t } = useI18n()

const activeTab = ref('files')

// Files Management State
const loading = ref(false)
const documents = ref<KnowledgeDocument[]>([])
const categories = ref<string[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = ref(10)
const searchQuery = ref('')
const selectedCategory = ref<string>()

const modalVisible = ref(false)
const editingDoc = ref<KnowledgeDocument | null>(null)
const formData = ref<DocumentCreate>({
  title: '',
  content: '',
  category: '',
  tags: []
})
const tagInput = ref('')

// Search Modal State
const searchModalVisible = ref(false)
const searchQueryText = ref('')
const searchResults = ref<SearchResult[]>([])
const searchLoading = ref(false)

// Directory Mapping State
const mappings = ref<DirectoryMapping[]>([])
const mappingModalVisible = ref(false)
const mappingFormData = ref<MappingCreate>({
  directoryName: '',
  directoryPath: '',
  fileSystem: 'NFS'
})
const mappingDetailVisible = ref(false)
const selectedMapping = ref<DirectoryMapping | null>(null)

// Fetch documents
const fetchDocuments = async () => {
  try {
    loading.value = true
    const response = await knowledgeApi.getDocuments({
      skip: (page.value - 1) * pageSize.value,
      limit: pageSize.value,
      category: selectedCategory.value,
      search: searchQuery.value || undefined,
    })
    documents.value = response.documents || []
    total.value = response.total || 0
  } catch (error) {
    ElMessage.error(t('knowledge.files.fetchFailed'))
  } finally {
    loading.value = false
  }
}

// Fetch categories
const fetchCategories = async () => {
  try {
    const data = await knowledgeApi.getCategories()
    categories.value = data || []
  } catch (error) {
    console.error('Failed to fetch categories:', error)
  }
}

// Handle add
const handleAdd = () => {
  editingDoc.value = null
  formData.value = {
    title: '',
    content: '',
    category: '',
    tags: []
  }
  modalVisible.value = true
}

// Handle edit
const handleEdit = (record: KnowledgeDocument) => {
  editingDoc.value = record
  formData.value = {
    title: record.title,
    content: record.content,
    category: record.category,
    tags: [...(record.tags || [])]
  }
  modalVisible.value = true
}

// Handle delete
const handleDelete = async (id: string) => {
  try {
    await ElMessageBox.confirm(
      t('knowledge.files.deleteConfirm'),
      'Warning',
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning',
      }
    )
    await knowledgeApi.deleteDocument(id)
    ElMessage.success(t('knowledge.files.deleteSuccess'))
    fetchDocuments()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('knowledge.files.deleteFailed'))
    }
  }
}

// Handle submit
const handleSubmit = async () => {
  try {
    if (editingDoc.value) {
      const updateData: DocumentUpdate = {
        title: formData.value.title,
        content: formData.value.content,
        category: formData.value.category,
        tags: formData.value.tags,
      }
      await knowledgeApi.updateDocument(editingDoc.value.id, updateData)
      ElMessage.success(t('knowledge.files.updateSuccess'))
    } else {
      await knowledgeApi.createDocument(formData.value)
      ElMessage.success(t('knowledge.files.createSuccess'))
    }
    modalVisible.value = false
    fetchDocuments()
    fetchCategories()
  } catch (error) {
    ElMessage.error(editingDoc.value ? t('knowledge.files.updateFailed') : t('knowledge.files.createFailed'))
  }
}

// Handle search
const handleSemanticSearch = async () => {
  if (!searchQueryText.value.trim()) {
    ElMessage.warning(t('knowledge.files.searchWarning'))
    return
  }
  try {
    searchLoading.value = true
    const results = await knowledgeApi.semanticSearch(searchQueryText.value, 5, selectedCategory.value)
    searchResults.value = results || []
  } catch (error) {
    ElMessage.error(t('knowledge.files.searchFailed'))
  } finally {
    searchLoading.value = false
  }
}

// Handle tags
const handleTagInput = () => {
  if (tagInput.value && !formData.value.tags.includes(tagInput.value)) {
    formData.value.tags.push(tagInput.value)
    tagInput.value = ''
  }
}

const removeTag = (tag: string) => {
  const index = formData.value.tags.indexOf(tag)
  if (index > -1) {
    formData.value.tags.splice(index, 1)
  }
}

// ==================== Directory Mapping Methods ====================
// Fetch mappings
const fetchMappings = async () => {
  try {
    const response = await knowledgeApi.getMappings()
    mappings.value = response.mappings || []
  } catch (error) {
    ElMessage.error(t('knowledge.mappings.fetchFailed'))
  }
}

// Handle add mapping
const handleAddMapping = () => {
  mappingFormData.value = {
    directoryName: '',
    directoryPath: '',
    fileSystem: 'NFS'
  }
  mappingModalVisible.value = true
}

// Handle submit mapping
const handleSubmitMapping = async () => {
  try {
    await knowledgeApi.createMapping(mappingFormData.value)
    ElMessage.success(t('knowledge.mappings.addSuccess'))
    mappingModalVisible.value = false
    fetchMappings()
  } catch (error) {
    ElMessage.error(t('knowledge.mappings.addFailed'))
  }
}

// Handle delete mapping
const handleDeleteMapping = async (id: string) => {
  try {
    await ElMessageBox.confirm(
      t('knowledge.mappings.deleteConfirm'),
      'Warning',
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning',
      }
    )
    await knowledgeApi.deleteMapping(id)
    ElMessage.success(t('knowledge.mappings.deleteSuccess'))
    fetchMappings()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('knowledge.mappings.deleteFailed'))
    }
  }
}

// Handle view mapping detail
const handleViewMapping = (mapping: DirectoryMapping) => {
  selectedMapping.value = mapping
  mappingDetailVisible.value = true
}

// Handle execute mapping
const handleExecuteMapping = async (id: string) => {
  try {
    ElMessage.info(t('knowledge.mappings.executeMessage'))
    // API call to execute mapping would go here
    // For now, just show a success message
    await new Promise(resolve => setTimeout(resolve, 1000))
    ElMessage.success(t('knowledge.mappings.executeSuccess', { id }))
  } catch (error) {
    ElMessage.error(t('knowledge.mappings.executeFailed'))
  }
}

// Statistics
const vectorizedCount = computed(() => documents.value.filter(d => d.vectorized).length)

// Watch for changes
watch([page, pageSize, searchQuery, selectedCategory], () => {
  if (activeTab.value === 'files') {
    fetchDocuments()
  }
})

watch(activeTab, (newTab) => {
  if (newTab === 'files') {
    fetchDocuments()
    fetchCategories()
  } else if (newTab === 'mappings') {
    fetchMappings()
  }
})

onMounted(() => {
  if (activeTab.value === 'files') {
    fetchDocuments()
    fetchCategories()
  }
})
</script>

<template>
  <div class="page-container">
    <div class="page-header">
      <h1 class="page-title">{{ t('knowledge.title') }}</h1>
    </div>

    <el-tabs v-model="activeTab" type="border-card">
      <!-- Files Management Tab -->
      <el-tab-pane :label="t('knowledge.tabs.files')" name="files">
        <!-- Statistics -->
        <el-row :gutter="16" class="mb-16">
          <el-col :span="8">
            <el-card>
              <el-statistic :title="t('knowledge.files.statsTotal')" :value="total" />
            </el-card>
          </el-col>
          <el-col :span="8">
            <el-card>
              <el-statistic :title="t('knowledge.files.statsIndexed')" :value="vectorizedCount" />
            </el-card>
          </el-col>
          <el-col :span="8">
            <el-card>
              <el-statistic :title="t('knowledge.files.statsCategories')" :value="categories.length" />
            </el-card>
          </el-col>
        </el-row>

        <!-- Toolbar -->
        <div class="table-header">
          <div class="header-filters">
            <el-input
              v-model="searchQuery"
              :placeholder="t('knowledge.files.searchPlaceholder')"
              clearable
              style="width: 300px; margin-right: 12px"
              @keyup.enter="fetchDocuments"
            >
              <template #append>
                <el-button :icon="Search" @click="fetchDocuments" />
              </template>
            </el-input>

            <el-select
              v-model="selectedCategory"
              :placeholder="t('knowledge.files.categoryPlaceholder')"
              clearable
              style="width: 150px"
              @change="fetchDocuments"
            >
              <el-option
                v-for="cat in categories"
                :key="cat"
                :label="cat"
                :value="cat"
              />
            </el-select>
          </div>

          <div class="header-actions">
            <el-button :icon="Search" @click="searchModalVisible = true">
              {{ t('knowledge.files.semanticSearch') }}
            </el-button>
            <el-button :icon="Refresh" @click="fetchDocuments">
              {{ t('common.refresh') }}
            </el-button>
            <el-button type="primary" :icon="Plus" @click="handleAdd">
              {{ t('knowledge.files.addButton') }}
            </el-button>
          </div>
        </div>

        <!-- Table -->
        <el-table
          v-loading="loading"
          :data="documents"
          stripe
          style="width: 100%"
        >
          <el-table-column prop="title" :label="t('knowledge.files.colTitle')" min-width="180" header-align="center" show-overflow-tooltip />
          <el-table-column prop="category" :label="t('knowledge.files.colCategory')" min-width="120" header-align="center" />
          <el-table-column :label="t('knowledge.files.colTags')" min-width="150" header-align="center">
            <template #default="{ row }">
              <el-tag
                v-for="tag in row.tags"
                :key="tag"
                size="small"
                style="margin-right: 4px"
              >
                {{ tag }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('knowledge.files.colVectorized')" width="100" header-align="center">
            <template #default="{ row }">
              <el-tag :type="row.vectorized ? 'success' : 'info'" size="small">
                {{ row.vectorized ? t('knowledge.files.colIndexed') : t('knowledge.files.colNotIndexed') }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t('knowledge.files.colUpdateTime')" width="170" header-align="center">
            <template #default="{ row }">
              {{ new Date(row.updated_at).toLocaleString('zh-CN') }}
            </template>
          </el-table-column>
          <el-table-column :label="t('common.actions')" width="150" fixed="right" header-align="center">
            <template #default="{ row }">
              <el-button
                type="primary"
                size="small"
                :icon="Edit"
                link
                @click="handleEdit(row)"
              >
                {{ t('common.edit') }}
              </el-button>
              <el-button
                type="danger"
                size="small"
                :icon="Delete"
                link
                @click="handleDelete(row.id)"
              >
                {{ t('common.delete') }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>

        <!-- Pagination -->
        <el-pagination
          v-model:current-page="page"
          v-model:page-size="pageSize"
          :page-sizes="[10, 20, 50, 100]"
          :total="total"
          layout="total, sizes, prev, pager, next, jumper"
          class="mt-24"
        />
      </el-tab-pane>

      <!-- Directory Mappings Tab -->
      <el-tab-pane name="mappings">
        <template #label>
          <el-icon><Link /></el-icon>
          <span>{{ t('knowledge.tabs.mappings') }}</span>
        </template>

        <el-alert
          :title="t('knowledge.mappings.description')"
          type="info"
          :description="t('knowledge.mappings.descriptionText')"
          :closable="false"
          show-icon
          style="margin-bottom: 16px"
        />

        <!-- Toolbar -->
        <div class="table-header">
          <div class="header-filters"></div>
          <div class="header-actions">
            <el-button type="primary" :icon="Plus" @click="handleAddMapping">
              {{ t('knowledge.mappings.addButton') }}
            </el-button>
          </div>
        </div>

        <!-- Table -->
        <el-table
          :data="mappings"
          stripe
          style="width: 100%"
        >
          <el-table-column :label="t('knowledge.mappings.taskId')" width="100" header-align="center">
            <template #default="{ row }">
              <el-tag type="primary">{{ row.id }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column
            prop="directory_name"
            :label="t('knowledge.mappings.directoryName')"
            min-width="140"
            header-align="center"
            show-overflow-tooltip
          />
          <el-table-column
            prop="directory_path"
            :label="t('knowledge.mappings.directoryPath')"
            min-width="220"
            show-overflow-tooltip
            header-align="center"
          />
          <el-table-column :label="t('knowledge.mappings.fileSystem')" width="90" header-align="center">
            <template #default="{ row }">
              <el-tag
                :type="row.file_system === 'NFS' ? 'primary' : row.file_system === 'S3' ? 'success' : 'warning'"
                size="small"
              >
                {{ row.file_system }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column
            prop="last_import_time"
            :label="t('knowledge.mappings.lastImportTime')"
            width="170"
            header-align="center"
          />
          <el-table-column
            prop="operator"
            :label="t('knowledge.mappings.operator')"
            min-width="100"
            header-align="center"
          />
          <el-table-column :label="t('knowledge.mappings.actions')" width="200" fixed="right" header-align="center">
            <template #default="{ row }">
              <el-button
                type="primary"
                size="small"
                :icon="Search"
                link
                @click="handleViewMapping(row)"
              >
                {{ t('knowledge.mappings.view') }}
              </el-button>
              <el-button
                type="success"
                size="small"
                :icon="Refresh"
                link
                @click="handleExecuteMapping(row.id)"
              >
                {{ t('knowledge.mappings.execute') }}
              </el-button>
              <el-button
                type="danger"
                size="small"
                :icon="Delete"
                link
                @click="handleDeleteMapping(row.id)"
              >
                {{ t('common.delete') }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <!-- Introduction Tab -->
      <el-tab-pane :label="t('knowledge.tabs.intro')" name="intro">
        <el-card>
          <template #header>
            <div class="card-header">
              <el-icon><InfoFilled /></el-icon>
              <span>{{ t('knowledge.intro.info') }}</span>
            </div>
          </template>

          <el-descriptions :column="2" border>
            <el-descriptions-item :label="t('knowledge.intro.name')">
              {{ t('knowledge.intro.nameValue') }}
            </el-descriptions-item>
            <el-descriptions-item :label="t('knowledge.intro.totalDocs')">
              {{ total }}
            </el-descriptions-item>
            <el-descriptions-item :label="t('knowledge.intro.indexedDocs')">
              {{ vectorizedCount }}
            </el-descriptions-item>
            <el-descriptions-item :label="t('knowledge.intro.categoryCount')">
              {{ categories.length }}
            </el-descriptions-item>
          </el-descriptions>

          <el-divider />

          <div>
            <h4>{{ t('knowledge.intro.description') }}</h4>
            <p>{{ t('knowledge.intro.descriptionText') }}</p>
          </div>
        </el-card>
      </el-tab-pane>
    </el-tabs>

    <!-- Add/Edit Modal -->
    <el-dialog
      v-model="modalVisible"
      :title="editingDoc ? t('knowledge.files.editModalTitle') : t('knowledge.files.addModalTitle')"
      width="600px"
    >
      <el-form :model="formData" label-width="100px">
        <el-form-item :label="t('knowledge.files.titleLabel')" required>
          <el-input
            v-model="formData.title"
            :placeholder="t('knowledge.files.titlePlaceholder')"
          />
        </el-form-item>

        <el-form-item :label="t('knowledge.files.categoryLabel')" required>
          <el-select
            v-model="formData.category"
            :placeholder="t('knowledge.files.modalCategoryPlaceholder')"
            filterable
            allow-create
            style="width: 100%"
          >
            <el-option
              v-for="cat in categories"
              :key="cat"
              :label="cat"
              :value="cat"
            />
          </el-select>
          <div class="form-help">{{ t('knowledge.files.categoryHelp') }}</div>
        </el-form-item>

        <el-form-item :label="t('knowledge.files.tagsLabel')">
          <div class="tags-input">
            <el-tag
              v-for="tag in formData.tags"
              :key="tag"
              closable
              @close="removeTag(tag)"
              style="margin-right: 8px; margin-bottom: 8px"
            >
              {{ tag }}
            </el-tag>
            <el-input
              v-model="tagInput"
              :placeholder="t('knowledge.files.tagsPlaceholder')"
              style="width: 200px"
              @keyup.enter="handleTagInput"
            />
          </div>
        </el-form-item>

        <el-form-item :label="t('knowledge.files.contentLabel')" required>
          <el-input
            v-model="formData.content"
            type="textarea"
            :rows="8"
            :placeholder="t('knowledge.files.contentPlaceholder')"
          />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="modalVisible = false">
          {{ t('common.cancel') }}
        </el-button>
        <el-button type="primary" @click="handleSubmit">
          {{ t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>

    <!-- Semantic Search Modal -->
    <el-dialog
      v-model="searchModalVisible"
      :title="t('knowledge.files.searchModalTitle')"
      width="800px"
    >
      <el-input
        v-model="searchQueryText"
        type="textarea"
        :rows="3"
        :placeholder="t('knowledge.files.searchModalPlaceholder')"
      />

      <template #footer>
        <el-button @click="searchModalVisible = false">
          {{ t('common.cancel') }}
        </el-button>
        <el-button type="primary" :loading="searchLoading" @click="handleSemanticSearch">
          {{ t('common.search') }}
        </el-button>
      </template>

      <div v-if="searchResults.length > 0" class="search-results mt-24">
        <h4>{{ t('knowledge.files.searchResults') }}</h4>
        <el-card
          v-for="result in searchResults"
          :key="result.id"
          class="result-card mb-16"
        >
          <div class="result-header">
            <h5>{{ result.title }}</h5>
            <el-tag type="info" size="small">
              {{ t('knowledge.files.similarity') }}: {{ (result.similarity_score * 100).toFixed(1) }}%
            </el-tag>
          </div>
          <p class="result-content">{{ result.content }}</p>
          <div class="result-meta">
            <el-tag size="small">{{ result.category }}</el-tag>
            <el-tag
              v-for="tag in result.tags"
              :key="tag"
              size="small"
              style="margin-left: 4px"
            >
              {{ tag }}
            </el-tag>
          </div>
        </el-card>
      </div>
    </el-dialog>

    <!-- Add Mapping Modal -->
    <el-dialog
      v-model="mappingModalVisible"
      :title="t('knowledge.mappings.modalTitle')"
      width="600px"
    >
      <el-form :model="mappingFormData" label-width="140px">
        <el-form-item :label="t('knowledge.mappings.directoryNameLabel')" required>
          <el-input
            v-model="mappingFormData.directoryName"
            :placeholder="t('knowledge.mappings.directoryNamePlaceholder')"
          />
        </el-form-item>

        <el-form-item :label="t('knowledge.mappings.directoryPathLabel')" required>
          <el-input
            v-model="mappingFormData.directoryPath"
            :placeholder="t('knowledge.mappings.directoryPathPlaceholder')"
          />
        </el-form-item>

        <el-form-item :label="t('knowledge.mappings.fileSystemLabel')" required>
          <el-select
            v-model="mappingFormData.fileSystem"
            :placeholder="t('knowledge.mappings.fileSystemPlaceholder')"
            style="width: 100%"
          >
            <el-option value="NFS" :label="t('knowledge.mappings.fileSystemNFS')" />
            <el-option value="S3" :label="t('knowledge.mappings.fileSystemS3')" />
            <el-option value="LOCAL" :label="t('knowledge.mappings.fileSystemLOCAL')" />
          </el-select>
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="mappingModalVisible = false">
          {{ t('common.cancel') }}
        </el-button>
        <el-button type="primary" @click="handleSubmitMapping">
          {{ t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>

    <!-- Mapping Detail Modal -->
    <el-dialog
      v-model="mappingDetailVisible"
      :title="t('knowledge.mappings.detailTitle')"
      width="600px"
    >
      <el-descriptions v-if="selectedMapping" :column="2" border>
        <el-descriptions-item :label="t('knowledge.mappings.taskId')">
          <el-tag type="primary">{{ selectedMapping.id }}</el-tag>
        </el-descriptions-item>
        <el-descriptions-item :label="t('knowledge.mappings.directoryName')">
          {{ selectedMapping.directory_name }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('knowledge.mappings.directoryPath')" :span="2">
          {{ selectedMapping.directory_path }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('knowledge.mappings.fileSystem')">
          <el-tag
            :type="selectedMapping.file_system === 'NFS' ? 'primary' : selectedMapping.file_system === 'S3' ? 'success' : 'warning'"
          >
            {{ selectedMapping.file_system }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item :label="t('knowledge.mappings.lastImportTime')">
          {{ selectedMapping.last_import_time }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('knowledge.mappings.operator')" :span="2">
          {{ selectedMapping.operator }}
        </el-descriptions-item>
      </el-descriptions>
    </el-dialog>
  </div>
</template>

<style scoped>
.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.header-filters {
  display: flex;
  gap: 12px;
}

.header-actions {
  display: flex;
  gap: 8px;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
}

.form-help {
  font-size: 12px;
  color: #6B7280;
  margin-top: 4px;
}

.tags-input {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
}

.search-results {
  max-height: 400px;
  overflow-y: auto;
}

.result-card {
  border: 1px solid #E5E7EB;
}

.result-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.result-header h5 {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #111827;
}

.result-content {
  color: #6B7280;
  margin-bottom: 12px;
  line-height: 1.6;
}

.result-meta {
  display: flex;
  gap: 8px;
}
</style>
